import { Providers } from '@/providers';

import '@/theme/global.css';
import { Container as ContainerChakra } from '@chakra-ui/react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body>
      <Providers>
        <ContainerChakra maxWidth="full" h="100vh" p={0}>
          {children}
        </ContainerChakra>
      </Providers>
    </body>
  );
}
