[project]
authors = ["Luis Burigo"]
entry = "main.sw"
license = "Apache-2.0"
name = "marketplace"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }

[proxy]
enabled = true
address = "0xc905465054211ca2186d2afe389b1ead7d06d484168483c8cbdcd990665b50b1"