[project]
authors = ["Luis Burigo"]
entry = "main.sw"
license = "Apache-2.0"
name = "registry"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
lib = { path = "../../lib" }

[proxy]
enabled = true
address = "0x7002bba8272209a0a31c371401209d7f4201a1c03623537f61be78a5582e81dc"

