/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChildrensImport } from './routes/childrens'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ChildrensRoute = ChildrensImport.update({
  id: '/childrens',
  path: '/childrens',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/childrens': {
      id: '/childrens'
      path: '/childrens'
      fullPath: '/childrens'
      preLoaderRoute: typeof ChildrensImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/childrens': typeof ChildrensRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/childrens': typeof ChildrensRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/childrens': typeof ChildrensRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/childrens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/childrens'
  id: '__root__' | '/' | '/childrens'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildrensRoute: typeof ChildrensRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildrensRoute: ChildrensRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/childrens"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/childrens": {
      "filePath": "childrens.ts"
    }
  }
}
ROUTE_MANIFEST_END */
