version: '3'

services:
  fuel-core:
    platform: linux/amd64
    container_name: '${PROJECT:-fuel-node}_fuel-core'
    environment:
      NETWORK_NAME: '${PROJECT} local'
      MIN_GAS_PRICE: ${MIN_GAS_PRICE}
      # This is the private key of the consensus.PoA.signing_key in the chainConfig.json
      # this key is responsible for validating the transactions
      CONSENSUS_KEY: ${WALLET_SECRET}
    build: ./fuel-core
    ports:
      - '${FUEL_CORE_PORT:-4000}:4000'
    volumes:
      - fuel-core-db:/mnt/db
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 20

volumes:
  fuel-core-db:
    name: '${PROJECT:-fuel-node}_fuel-core-db'
