# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: manager
    address:
    - 0x39140d7233297276196c49bf13c78ce056083ca8bf61af2698ee3fdeb8af1a8b
    abi_file_path: abis/manager-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: ManagerLogEvent
      logId: '11146364172429795543'
