name: envio-indexer
ecosystem: fuel
contracts:
  - name: manager
    abi_file_path: abis/manager-abi.json
    handler: src/EventHandlers.ts
    events:
      - name: ManagerLogEvent
        logId: '11146364172429795543'
      - name: OwnerChangedEvent
        logId: '4160095253491321915'
      - name: ResolverChangedEvent
        logId: '2059351015524214332'
  - name: marketplace
    abi_file_path: abis/marketplace-abi.json
    handler: src/marketplace/EventHandlers.ts
    events:
      - name: AssetFeeAdjustedEvent
        logId: '10288224578490882859'
      - name: AssetAddedEvent
        logId: '10516624671986619165'
      - name: OrderCreatedEvent
        logId: '8887194707992577051'
      - name: OrderExecutedEvent
        logId: '1991902595969952905'
      - name: OrderCancelledEvent
        logId: '2995604236870753654'
      - name: OrderEditedEvent
        logId: '5596540746579447825'
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: manager
        address: 0x39140d7233297276196c49bf13c78ce056083ca8bf61af2698ee3fdeb8af1a8b
      - name: marketplace
        address: 0x3f1ec560123a1bbd929c03e4fde1cd54d4c3071a1efd00b427e4ad4b9ac730bb
  - id: 9889
    start_block: 0
    contracts:
      - name: manager
        address: 0x3ca7ac3db222a740e1c89158d9255afc2c3591ee3f34aedcaaf7cfeceebd0833
