import { Providers } from '@/providers';
import { Inter } from 'next/font/google';

import '@/theme/global.css';
import { Container as ContainerChakra } from '@chakra-ui/react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const interFont = Inter({
  weight: ['100', '200', '500', '900'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={interFont.className}>
      <body>
        <Providers>
          <ContainerChakra maxWidth="full" h="100vh" p={0}>
            {children}
          </ContainerChakra>
        </Providers>
      </body>
    </html>
  );
}
