/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.71.1
  Forc version: 0.48.1
  Fuel-Core version: 0.22.0
*/

export type { RegistryContractAbi } from './RegistryContractAbi';
export type { StorageContractAbi } from './StorageContractAbi';
export type { TestContractAbi } from './TestContractAbi';

export { RegistryContractAbi__factory } from './factories/RegistryContractAbi__factory';
export { StorageContractAbi__factory } from './factories/StorageContractAbi__factory';
export { TestContractAbi__factory } from './factories/TestContractAbi__factory';
