/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.81.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

import type {
  BigNumberish,
  BN,
  Bytes,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
  StdString,
} from 'fuels';

import type { Enum } from "./common";

export enum RegistryTestContractErrorInput { DomainUnavailable = 'DomainUnavailable', DomainExpired = 'DomainExpired' };
export enum RegistryTestContractErrorOutput { DomainUnavailable = 'DomainUnavailable', DomainExpired = 'DomainExpired' };

export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;
export type GracePeriodInput = { timestamp: BigNumberish, period: BigNumberish, grace_period: BigNumberish };
export type GracePeriodOutput = { timestamp: BN, period: BN, grace_period: BN };
export type RawBytesInput = { ptr: BigNumberish, cap: BigNumberish };
export type RawBytesOutput = { ptr: BN, cap: BN };

interface RegistryTestContractAbiInterface extends Interface {
  functions: {
    calculate_domain_price: FunctionFragment;
    get_all: FunctionFragment;
    get_grace_period: FunctionFragment;
    register: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'calculate_domain_price', values: [StdString, BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_all', values: [string, ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_grace_period', values: [StdString]): Uint8Array;
  encodeFunctionData(functionFragment: 'register', values: [StdString, string, BigNumberish, BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'calculate_domain_price', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_all', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_grace_period', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'register', data: BytesLike): DecodedValue;
}

export class RegistryTestContractAbi extends Contract {
  interface: RegistryTestContractAbiInterface;
  functions: {
    calculate_domain_price: InvokeFunction<[domain: StdString, period: BigNumberish], BN>;
    get_all: InvokeFunction<[owner: string, bako_id: ContractIdInput], Bytes>;
    get_grace_period: InvokeFunction<[owner: StdString], GracePeriodOutput>;
    register: InvokeFunction<[name: StdString, resolver: string, period: BigNumberish, timestamp: BigNumberish], void>;
  };
}
