/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.90.0
  Forc version: 0.60.0
  Fuel-Core version: 0.30.0
*/

import type {
  BigNumberish,
  BN,
  Bytes,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
  StdString,
} from 'fuels';

import type { Enum } from "./common";

export enum RegistryTestContractErrorInput { DomainUnavailable = 'DomainUnavailable', InvalidAmount = 'InvalidAmount', DomainExpired = 'DomainExpired' };
export enum RegistryTestContractErrorOutput { DomainUnavailable = 'DomainUnavailable', InvalidAmount = 'InvalidAmount', DomainExpired = 'DomainExpired' };

export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type GracePeriodInput = { timestamp: BigNumberish, period: BigNumberish, grace_period: BigNumberish };
export type GracePeriodOutput = { timestamp: BN, period: BN, grace_period: BN };

interface RegistryTestContractAbiInterface extends Interface {
  functions: {
    calculate_domain_price: FunctionFragment;
    get_all: FunctionFragment;
    get_grace_period: FunctionFragment;
    register: FunctionFragment;
  };
}

export class RegistryTestContractAbi extends Contract {
  interface: RegistryTestContractAbiInterface;
  functions: {
    calculate_domain_price: InvokeFunction<[domain: StdString, period: BigNumberish], BN>;
    get_all: InvokeFunction<[owner: string, bako_id: ContractIdInput], Bytes>;
    get_grace_period: InvokeFunction<[owner: StdString], GracePeriodOutput>;
    register: InvokeFunction<[name: StdString, resolver: string, period: BigNumberish, timestamp: BigNumberish], void>;
  };
}
