/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.71.1
  Forc version: 0.48.1
  Fuel-Core version: 0.22.0
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;

interface TestContractAbiInterface extends Interface {
  functions: {
    test_get: FunctionFragment;
    test_set: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'test_get',
    values: [ContractIdInput]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: 'test_set',
    values: [ContractIdInput]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: 'test_get',
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: 'test_set',
    data: BytesLike
  ): DecodedValue;
}

export class TestContractAbi extends Contract {
  interface: TestContractAbiInterface;
  functions: {
    test_get: InvokeFunction<[storage_id: ContractIdInput], void>;
    test_set: InvokeFunction<[storage_id: ContractIdInput], void>;
  };
}
