/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.73.0
  Forc version: 0.49.2
  Fuel-Core version: 0.22.0
*/

export type { RegistryContractAbi } from './RegistryContractAbi';
export type { StorageContractAbi } from './StorageContractAbi';

export { RegistryContractAbi__factory } from './factories/RegistryContractAbi__factory';
export { StorageContractAbi__factory } from './factories/StorageContractAbi__factory';
