name: envio-indexer
ecosystem: fuel
contracts:
  - name: marketplace
    abi_file_path: abis/marketplace-abi.json
    handler: src/EventHandlers.ts
    events:
      - name: AssetFeeAdjustedEvent
        logId: '10288224578490882859'
      - name: AssetAddedEvent2
        logId: '10985593674862968702'
      - name: OrderCreatedEvent
        logId: '8887194707992577051'
      - name: OrderExecutedEvent
        logId: '1991902595969952905'
      - name: OrderCancelledEvent
        logId: '2995604236870753654'
      - name: OrderEditedEvent
        logId: '5596540746579447825'
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: marketplace
        address: 0xc905465054211ca2186d2afe389b1ead7d06d484168483c8cbdcd990665b50b1
  - id: 9889
    start_block: 0
    contracts:
      - name: marketplace
        address: 0x7722e9314e1efbef5a18545a2440b79dac36cfc2f22d0d27bd0c1e4f2ec6df15
