[project]
authors = ["Luis Burigo"]
entry = "main.sw"
license = "Apache-2.0"
name = "manager"

[dependencies]
lib = { path = "../../lib" }

[proxy]
enabled = true
address = "0x324a2d168efd2e999156812c8edf51df68c110dd5afa4bd5fd83219f2382e3d2"