[project]
authors = ["Luis Burigo"]
entry = "main.sw"
license = "Apache-2.0"
name = "manager"

[dependencies]
lib = { path = "../../lib" }

[proxy]
enabled = true
# Mainnet
#address = "0x0d69e157eba419749d3e3427030b76151f2ed980cb4b1f16fff72b13dc56f2f2"

# Testnet
address = "0x324a2d168efd2e999156812c8edf51df68c110dd5afa4bd5fd83219f2382e3d2"