[project]
authors = ["Luis Burigo"]
entry = "main.sw"
license = "Apache-2.0"
name = "manager"

[dependencies]
lib = { path = "../../lib" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }

[proxy]
enabled = true
address = "0xe471f59b3aec58d2f352785135b25110d1904fd5f08547859a89082719f62172"