/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.90.0
*/

export { ManagerContract } from './ManagerContract.js';
export { ManagerContractFactory } from './ManagerContractFactory.js';
export { RegisterContract } from './RegisterContract.js';
export { RegisterContractFactory } from './RegisterContractFactory.js';
