name: UI E2E Tests

on:
  - pull_request

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build UI
        run: pnpm build:ui

      - name: Install Playwright Browsers
        run: |
          cd apps/ui  
          pnpm exec playwright install --with-deps

      - name: Build UI test mode
        run: |
          cd apps/ui
          pnpm vite build --mode test

      - name: Run Playwright tests
        run: | 
          cd apps/ui
          xvfb-run -a pnpm exec playwright test

      - name: Upload report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
